python beit3/run_beit3_finetuning.py \
        --model beit3_base_patch16_384 \
        --input_size 384 \
        --task coco_retrieval \
        --batch_size 6 \
        --layer_decay 0.65 \
        --lr 2e-4 \
        --epochs 1 \
        --warmup_epochs 1 \
        --drop_path 0.2 \
        --sentencepiece_model beit3/beit3.spm \
        --finetune beit3/beit3_base_itc_patch16_224.pth \
        --data_path D:/Projects/doan \
        --output_dir beit3_ckpt \
        --log_dir beit3_logs \
        --weight_decay 0.05 \
        --update_freq 4 \
        --num_workers 14 \
        --seed 42 \
        --save_ckpt_freq 5 \
        --checkpoint_activations

